export const SOBRE_MI_AGREGADO = 'SOBRE_MI_AGREGADO';

/* imagen */
export const IMAGEN_CARGADA = 'IMAGEN_CARGADA';
export const IMAGEN_ELIMINADA = 'IMAGEN_ELIMINADA';

/* experiencia laboral */
export const EXPERIENCIA_LABORAL_AGREGADA =
	'EXPERIENCIA_LABORAL_AGREGADA';
export const ELIMINAR_EXPERIENCIA = 'ELIMINAR_EXPERIENCIA';
export const OBTENER_EXPERIENCIA = 'OBTENER_EXPERIENCIA';
export const EDITAR_EXPERIENCIA = 'EDITAR_EXPERIENCIA';
/* export const GUARDAR_EXPERIENCIA_EDITADA =
	'GUARDAR_EXPERIENCIA_EDITADA'; */
export const FIN_EDICION_EXPERIENCIA = 'FIN_EDICION_EXPERIENCIA';

/* estudios */
export const ESTUDIO_AGREGADO = 'ESTUDIO_AGREGADO';
export const ELIMINAR_ESTUDIO = 'ELIMINAR_ESTUDIO';
export const OBTENER_ESTUDIO = 'OBTENER_ESTUDIO';
export const EDITAR_ESTUDIO = 'EDITAR_ESTUDIO';
export const FIN_EDICION_ESTUDIO = 'FIN_EDICION_ESTUDIO';

/* habilidades */
export const HABILIDAD_AGREGADA = 'HABILIDAD_AGREGADA';
export const ELIMINAR_HABILIDAD = 'ELIMINAR_HABILIDAD';
